### ISSUE TITLE
Error receiving blobs: An internal error occurred. [128]

### ISSUE THREAD

**Issue by flyingbird** [neal/savethemblobs#3]
Fetching firmwares Apple is currently signing for iPhone7,1
Requesting blobs from Apple for iPhone7,1/12B440
Error receiving blobs: An internal error occurred. [128]
@Neal
http://gs.apple.com/TSS/controller?action=2
This post request for iOS8.1.2 fails.

**Comment by waja** [comment]
This worked on 9th Dec. 2014 for 8.1.2 and iPhone7,2, but actually the next try at 27th Jan. and later failes with the same error

**Comment by neal** [comment]
This should be fixed now. Thanks for reporting.

**Comment by iAdam1n** [comment]
This is also happening on iOS 8.2 now. Needs fixing after every iOS update?
