### ISSUE TITLE
Not pulling blob for iOS 9.3

### ISSUE THREAD

**Issue by warthog3** [neal/savethemblobs#5]
This is the output I see after today when I would expect the blob for 9.3 to be pulled:

`Fetching firmwares Apple is currently signing for iPhone6,1
Skipping build 13D15; blobs already exist at /Users/me/.shsh/ECID_iPhone6,1_9.2.1-13D15.shsh
Fetching blobs available on Cydia server
No blobs found on Cydia server
Fetching blobs available on iFaith server
No blobs found on iFaith server
localhost-2:savethemblobs-master me$`

**Comment by jevinskie** [comment]
I got 9.3 blobs for: iPad2,5 (one device), iPad4,1 (one device), iPad4,4 (ten devices). Devices that have successfully fetched 9.2.1 blobs but have not fetched 9.3 blobs are: iPhone8,1, iPod7,1, iPod5,1, iPhone4,1.

**Comment by jevinskie** [comment]
Looks like the issue isn't in the STB client but in Neil's api.ineil.me server.

`Fetching firmwares Apple is currently signing for iPhone6,1
resp: {
    "iPhone6,1":{
        "board":"n51ap",
        "model":"iPhone6,1",
        "cpid":"35168",
        "bdid":"0",
        "platform":"s5l8960x",
        "firmwares":[
            {
                "build":"13D15",
                "version":"9.2.1",
                "signing":true,
                "started":"2016-01-12",
                "stopped":null
            }
        ]
    }
}`

**Comment by warthog3** [comment]
Was able to pull blob for 9.3 yesterday before Apple stopped signing for it.
